name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Leave a friendly comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          # This line automatically finds the right ID number for both PRs and Issues
          issue-number: ${{ github.event.pull_request.number || github.event.issue.number }}
          body: |
            Hi there! 👋 Thank you for interacting with this project. 
            Our robots and team will take a look at this soon!

